/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

// Import Routes

import { Route as rootRoute } from './routes/__root'
import { Route as PerfAiOmeImport } from './routes/perf-ai-ome'
import { Route as ProtectedImport } from './routes/_protected'
import { Route as ProtectedIndexImport } from './routes/_protected/index'
import { Route as ProtectedPreferencesImport } from './routes/_protected/preferences'
import { Route as ProtectedFeedIndexImport } from './routes/_protected/feed/index'
import { Route as ProtectedFeedIdImport } from './routes/_protected/feed/$id'

// Create/Update Routes

const PerfAiOmeRoute = PerfAiOmeImport.update({
  id: '/perf-ai-ome',
  path: '/perf-ai-ome',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedRoute = ProtectedImport.update({
  id: '/_protected',
  getParentRoute: () => rootRoute,
} as any)

const ProtectedIndexRoute = ProtectedIndexImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedPreferencesRoute = ProtectedPreferencesImport.update({
  id: '/preferences',
  path: '/preferences',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedFeedIndexRoute = ProtectedFeedIndexImport.update({
  id: '/feed/',
  path: '/feed/',
  getParentRoute: () => ProtectedRoute,
} as any)

const ProtectedFeedIdRoute = ProtectedFeedIdImport.update({
  id: '/feed/$id',
  path: '/feed/$id',
  getParentRoute: () => ProtectedRoute,
} as any)

// Populate the FileRoutesByPath interface

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/_protected': {
      id: '/_protected'
      path: ''
      fullPath: ''
      preLoaderRoute: typeof ProtectedImport
      parentRoute: typeof rootRoute
    }
    '/perf-ai-ome': {
      id: '/perf-ai-ome'
      path: '/perf-ai-ome'
      fullPath: '/perf-ai-ome'
      preLoaderRoute: typeof PerfAiOmeImport
      parentRoute: typeof rootRoute
    }
    '/_protected/preferences': {
      id: '/_protected/preferences'
      path: '/preferences'
      fullPath: '/preferences'
      preLoaderRoute: typeof ProtectedPreferencesImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/': {
      id: '/_protected/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof ProtectedIndexImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/feed/$id': {
      id: '/_protected/feed/$id'
      path: '/feed/$id'
      fullPath: '/feed/$id'
      preLoaderRoute: typeof ProtectedFeedIdImport
      parentRoute: typeof ProtectedImport
    }
    '/_protected/feed/': {
      id: '/_protected/feed/'
      path: '/feed'
      fullPath: '/feed'
      preLoaderRoute: typeof ProtectedFeedIndexImport
      parentRoute: typeof ProtectedImport
    }
  }
}

// Create and export the route tree

interface ProtectedRouteChildren {
  ProtectedPreferencesRoute: typeof ProtectedPreferencesRoute
  ProtectedIndexRoute: typeof ProtectedIndexRoute
  ProtectedFeedIdRoute: typeof ProtectedFeedIdRoute
  ProtectedFeedIndexRoute: typeof ProtectedFeedIndexRoute
}

const ProtectedRouteChildren: ProtectedRouteChildren = {
  ProtectedPreferencesRoute: ProtectedPreferencesRoute,
  ProtectedIndexRoute: ProtectedIndexRoute,
  ProtectedFeedIdRoute: ProtectedFeedIdRoute,
  ProtectedFeedIndexRoute: ProtectedFeedIndexRoute,
}

const ProtectedRouteWithChildren = ProtectedRoute._addFileChildren(
  ProtectedRouteChildren,
)

export interface FileRoutesByFullPath {
  '': typeof ProtectedRouteWithChildren
  '/perf-ai-ome': typeof PerfAiOmeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/': typeof ProtectedIndexRoute
  '/feed/$id': typeof ProtectedFeedIdRoute
  '/feed': typeof ProtectedFeedIndexRoute
}

export interface FileRoutesByTo {
  '/perf-ai-ome': typeof PerfAiOmeRoute
  '/preferences': typeof ProtectedPreferencesRoute
  '/': typeof ProtectedIndexRoute
  '/feed/$id': typeof ProtectedFeedIdRoute
  '/feed': typeof ProtectedFeedIndexRoute
}

export interface FileRoutesById {
  __root__: typeof rootRoute
  '/_protected': typeof ProtectedRouteWithChildren
  '/perf-ai-ome': typeof PerfAiOmeRoute
  '/_protected/preferences': typeof ProtectedPreferencesRoute
  '/_protected/': typeof ProtectedIndexRoute
  '/_protected/feed/$id': typeof ProtectedFeedIdRoute
  '/_protected/feed/': typeof ProtectedFeedIndexRoute
}

export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths: '' | '/perf-ai-ome' | '/preferences' | '/' | '/feed/$id' | '/feed'
  fileRoutesByTo: FileRoutesByTo
  to: '/perf-ai-ome' | '/preferences' | '/' | '/feed/$id' | '/feed'
  id:
    | '__root__'
    | '/_protected'
    | '/perf-ai-ome'
    | '/_protected/preferences'
    | '/_protected/'
    | '/_protected/feed/$id'
    | '/_protected/feed/'
  fileRoutesById: FileRoutesById
}

export interface RootRouteChildren {
  ProtectedRoute: typeof ProtectedRouteWithChildren
  PerfAiOmeRoute: typeof PerfAiOmeRoute
}

const rootRouteChildren: RootRouteChildren = {
  ProtectedRoute: ProtectedRouteWithChildren,
  PerfAiOmeRoute: PerfAiOmeRoute,
}

export const routeTree = rootRoute
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

/* ROUTE_MANIFEST_START
{
  "routes": {
    "__root__": {
      "filePath": "__root.jsx",
      "children": [
        "/_protected",
        "/perf-ai-ome"
      ]
    },
    "/_protected": {
      "filePath": "_protected.jsx",
      "children": [
        "/_protected/preferences",
        "/_protected/",
        "/_protected/feed/$id",
        "/_protected/feed/"
      ]
    },
    "/perf-ai-ome": {
      "filePath": "perf-ai-ome.jsx"
    },
    "/_protected/preferences": {
      "filePath": "_protected/preferences.jsx",
      "parent": "/_protected"
    },
    "/_protected/": {
      "filePath": "_protected/index.jsx",
      "parent": "/_protected"
    },
    "/_protected/feed/$id": {
      "filePath": "_protected/feed/$id.jsx",
      "parent": "/_protected"
    },
    "/_protected/feed/": {
      "filePath": "_protected/feed/index.jsx",
      "parent": "/_protected"
    }
  }
}
ROUTE_MANIFEST_END */
